### ISSUE TITLE
gcc :error :../common/maskApi.c  no such file or directory

### ISSUE THREAD

**Issue by whxueChris** [cxliu0/OA-MIL#10]
Hello ! Thanks for sharing your great work.

When I  try to install OA-MIL, it encounted this error . Could you give me some suggestions ?

**Comment by cxliu0** [comment]
This error may be related to pycocotools. You may refer to [this issue](https://github.com/cocodataset/cocoapi/issues/141).

**Comment by whxueChris** [comment]
> This error may be related to pycocotools. You may refer to [this issue](https://github.com/cocodataset/cocoapi/issues/141).

Thank you for your kind reply. I follow the solution to this issue, but the problem still exists. What confuses me is the `maskApi.c` file already in the 'common 'directory. 
![image](https://github.com/cxliu0/OA-MIL/assets/50388024/74a4877e-6f27-4002-a5f0-577265a82c57)

**Comment by cxliu0** [comment]
Actually, we have not encountered this error before, so I am not sure what leads to the problem. Maybe you could try to initialize a new conda environment and install it again.

**Comment by whxueChris** [comment]
> Actually, we have not encountered this error before, so I am not sure what leads to the problem. Maybe you could try to initialize a new conda environment and install it again.

Sorry for the late reply. I have solved this issue by installing a low version cython. Cython == 0.29.33 works for me. [https://github.com/open-mmlab/mmdetection/issues/10730](url)
