### ISSUE TITLE
There are some errors when I train COCO

### ISSUE THREAD

**Issue by JiuqingDong** [cxliu0/OA-MIL#3]
Did you change the COCO format from .json to .pkl? I remember the original COCO annotation is  a .json file.

<img width="544" alt="Dataload" src="https://user-images.githubusercontent.com/111500217/188108521-62742546-046a-461e-a25f-727e889a308d.png">

When I try to train the fast-rcnn on COCO. I got the errors like this:
<img width="1118" alt="error" src="https://user-images.githubusercontent.com/111500217/188108572-5a7f06a0-211b-4436-b6ed-53591dd04899.png">

Maybe I didn't upload my dataset?

**Comment by cxliu0** [comment]
The format of COCO dataset is converted from .json to .pkl for saving loading time. 
Format conversion is done in "Data Preparation" step. You can refer to [utils/gen_noisy_coco.py](https://github.com/cxliu0/OA-MIL/blob/main/utils/gen_noisy_coco.py#L57) for format conversion.

**Comment by JiuqingDong** [comment]
When I train the original COCO, I got all evaluation metrics equal to 0 like the following:
I also trained the COCO dataset with noise and got the same results. 

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/111500217/188299502-ed5954a0-b979-4ead-ad04-32c55bf1dbb0.png">


I just run sh train_coco.sh, and I didn't change any parameters.

**Comment by cxliu0** [comment]
Did you preprocess the dataset correctly? Maybe there is something wrong with the training pkl file. Here is my preprocessed [coco2017_train.pkl](https://drive.google.com/file/d/14CjmFaKnWgdtT561CGvadeq6wGpmiLeo/view?usp=sharing), and you can compare your pkl file with it. BTW, I have run the code locally and the results are okay.

**Comment by JiuqingDong** [comment]
Sorry, I got a mistake. When the second time I upload your code. I forgot to install and make mmcv module, which  caused the model to generate a wrong dataset. Now, I can run the coco dataset. Thank you for your suggestion! I will train on a custom dataset.

**Comment by JiuqingDong** [comment]
By the way, Happy Mid-autumn festival.

**Comment by cxliu0** [comment]
Glad you have solved the issue :smile:
