### ISSUE TITLE
The result of the clean dataset

### ISSUE THREAD

**Issue by JiuqingDong** [cxliu0/OA-MIL#4]
Firstly, thank you for your code.

When I first time read your paper, I had a question: although you showed the result on a clean FasterRCNN, there is no result of OA-MIL on the clean dataset. Actually, I re-implemented your work and got the same result. The result shows that OA-MIL is more robust on a noisy dataset. But when I try to train FastRCNN and OA-MIL(FastRCNN) on clean COCO datasets, I found OA-MIL got a lower performance. The result is shown as follows:   

The result of Faster-RCNN, In your paper, mAP of CleanFasterRCNN on COCO dataset is 37.9, AP50 is 58.1
![Faster-RCNN](https://user-images.githubusercontent.com/111500217/189835899-a774d82d-9b60-427f-bf5c-3ac267d5aa00.png)

The result of Faster-RCNN-OAMIL, In your paper, there is no related result.
<img width="876" alt="Faster-RCNN-OA-MIL" src="https://user-images.githubusercontent.com/111500217/189834687-9d32da31-b97f-4271-8441-6458212b7549.png">

Are your results similar to mine? I'm wondering if my results are incorrect.

**Comment by cxliu0** [comment]
Actually, I have trained OA-MIL on clean VOC2007, and the performance of OAMIL-FasterRCNN is better than clean-FasterRCNN (78.6 vs. 77.2). This may also generalize to COCO,  but I did not validate this point. 

The reason you get inferior results may be that the default hyper-parameters are set for large box noise. Perhaps hyper-parameters tuning is needed to get better results on clean COCO dataset, e.g., use smaller [oamil_lambda](https://github.com/cxliu0/OA-MIL/blob/main/configs/_base_/models/faster_rcnn_r50_fpn_coco_oamil.py#L57), change [oais_gamma](https://github.com/cxliu0/OA-MIL/blob/main/configs/_base_/models/faster_rcnn_r50_fpn_coco_oamil.py#L62) and [oais_theta](https://github.com/cxliu0/OA-MIL/blob/main/configs/_base_/models/faster_rcnn_r50_fpn_coco_oamil.py#L63).

**Comment by JiuqingDong** [comment]
Thank you for your suggestion! I will check it.
