### ISSUE TITLE
I have some ideas which I want to discuss with you

### ISSUE THREAD

**Issue by JiuqingDong** [cxliu0/OA-MIL#6]
In your paper, you proposed an 'Object-Aware Instance Extension' module. You said that the extended object bags are subsequently used to train the instance selector. You do not extend negative bags. 

What I want to know is if there are some missing labels, these missing labels will be treated as negative samples, right? Is there any way to solve this problem of missing labels? 

Could you please give me some guidance? If there is a chance we can cooperate. This is my personal email dongjiuqing1996@gmail.com.

**Comment by cxliu0** [comment]
To my understanding, missing labels mean some objects are not annotated. However, this seems rare in standard object detection datasets. Therefore, we did not develop a specific strategy to deal with missing labels.

Did you concern that some negative bags may contain unannotated objects? If so, there may be two ways to deal with missing labels:
* A naive way, which follows the procedure of training->refining labels->retraining
   * Train the object detector and perform object detection on training images;
   * Compare the predictions and ground-truth boxes, fill up missing labels with extra predictions;
   * Retrain the object detector with new ground-truth labels.
 * The second way: simply ignoring the negative bags that may contain unannotated objects. This is based on the assumption that most images are correctly annotated. 
     * During training, negative bags that contain unannotated objects may have a significantly larger classification loss compared with normal negative samples. You can use a threshold to filter out these samples.

**Comment by JiuqingDong** [comment]
Thank you for your suggestion. I will try to do that.

**Comment by JiuqingDong** [comment]
Dear Auther,

I read your implementation. I have some questions as follows:
1.  In line 213 [https://github.com/cxliu0/OA-MIL/blob/main/mmdet/models/roi_heads/standard_roi_head_oamil.py](url)
You define a function '_instance_selection', and this function will return two result: oaie_scores_list, pseudo_bbox_targets.
I print these result, but I don't understand what does that mean?
<img width="1815" alt="image" src="https://user-images.githubusercontent.com/111500217/201047562-1ff902f8-8521-4645-8119-a6fe1d7e91a6.png">
 Does it mean that there are 132 (Case1) or 52 (Case2) pseudo_bbox_targets with confidence scores? if that, why are there too many pseudo_bbox_targets?

2. The second thing is that if the pseudo_bbox_targets is 4 coordinates, why are there negative numbers?
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/111500217/201048509-d4ae1115-c6d3-466f-b8d3-dbb56a05ff74.png">

3. The last question is, where is the best-selected instance?  How can I find the coordinates and category of the the best-selected instance?

I would appreciate it if you could help.

best regards.

**Comment by cxliu0** [comment]
1. 132 (Case1) or 52 (Case2) denote the number of positive instances, i.e., positive anchors, and ```confidence_scores``` contains the confidence scores of positive instances. Note that each positive instance corresponds to a ground-truth box. We define ```pseudo_bbox_targets```  as the new ground-truth of positive instances ([see definition here](https://github.com/cxliu0/OA-MIL/blob/main/mmdet/models/roi_heads/standard_roi_head_oamil.py#L277)). Therefore, it has the same size as positive instances.
2.  ```pseudo_bbox_targets``` is the decoded ground-truth targets, not the original coordinates in the image, so there are negative numbers.
3. The best-selected instance is defined in [L295](https://github.com/cxliu0/OA-MIL/blob/main/mmdet/models/roi_heads/standard_roi_head_oamil.py#L295). This is the original coordinates in the image. The category of positive instances is given by ```labels[pos_inds]```, so the category of best-selected instance can be subsequently obtained from this variable.

**Comment by JiuqingDong** [comment]
Thank you for your answers. Well, I believe it is a really good job. It inspires me to do some experiments, and it works on my own dataset.

**Comment by cxliu0** [comment]
Glad that this work is helpful to you.
