### ISSUE TITLE
About release plan for RetinaNet?

### ISSUE THREAD

**Issue by kangyeolk** [cxliu0/OA-MIL#7]
Thanks for your awesome work!
Could you release retina config files?

Thanks again.

**Comment by cxliu0** [comment]
Sorry, we recently have no plan to release RetinaNet. However, the OA-MIL parameters of RetinaNet were given in the paper, and the implementation is similar to OAMIL-FasterRCNN.

**Comment by kangyeolk** [comment]
Okay, Thanks for reply!
