### ISSUE TITLE
Can i use it with COCO dataset?

### ISSUE THREAD

**Issue by LeoGeralt** [cxliu0/OA-MIL#9]
Thanks for your sharing!I would like to use your method on remote sensing datasets, such as the Coco dataset.I wander if your method is also applicable to this dataset.If it's suitable，What should I do to transplant your method？

**Comment by cxliu0** [comment]
Our approach is applicable to the COCO (Microsoft Common Objects in Context)) dataset. If you would like to train our method on the clean version of the COCO dataset, you can follow [Data Preparation](https://github.com/cxliu0/OA-MIL#data-preparation) in README and set ```box_noise_level``` to ```0.0```.

**Comment by LeoGeralt** [comment]
I'm sorry，Actually i want to know if your method is suitable with DOTA dataset？（a kind of remote sensing dataset）

**Comment by cxliu0** [comment]
Theoretically, our approach is not limited to specific datasets. Therefore, I think our method is applicable to remote sensing datasets. You can follow the procedure below to transplant our method:

1. Create FasterRCNN configuration for the DOTA dataset following [faster_rcnn_r50_fpn_1x_coco_oamil.py](https://github.com/cxliu0/OA-MIL/blob/main/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco_oamil.py);
2. Initialize data configuration for the DOTA dataset following [voc07.py](https://github.com/cxliu0/OA-MIL/blob/main/configs/_base_/datasets/voc07.py) or [coco_detection.py](https://github.com/cxliu0/OA-MIL/blob/main/configs/_base_/datasets/coco_detection.py);
3. Customize dataloader for the DOTA dataset. For example, you can follow the dataloader of [VOC](https://github.com/cxliu0/OA-MIL/blob/main/mmdet/datasets/voc07.py) or [COCO](https://github.com/cxliu0/OA-MIL/blob/main/mmdet/datasets/coco.py) dataset;
4. Train the model on DOTA following [README](https://github.com/cxliu0/OA-MIL/tree/main#training). In addition, you may need to modify the [hyper-parameters](https://github.com/cxliu0/OA-MIL/blob/main/configs/_base_/models/faster_rcnn_r50_fpn_coco_oamil.py#L57) of OA-MIL to obtain good performance.

**Comment by LeoGeralt** [comment]
Thank you so much!!!
